package com.scanner.bridge.scanner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.util.List;

/**
 * Virtual scanner for testing. Returns a programmatically generated BMP image
 * simulating a scanned document. Active only when the "test" Spring profile is set.
 */
@Service
@Profile("test")
public class MockScannerImpl implements ScannerService {

    private static final Logger log = LoggerFactory.getLogger(MockScannerImpl.class);

    @Override
    public List<byte[]> scan(int maxPages) throws Exception {
        log.info("MockScanner: generating virtual scan image");
        // Generate a white A4-like image (794x1123 pixels at 96dpi) with sample text
        BufferedImage image = new BufferedImage(794, 1123, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        // White background
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, 794, 1123);
        // Header bar
        g.setColor(new Color(0x1a56db));
        g.fillRect(0, 0, 794, 60);
        g.setColor(Color.WHITE);
        g.setFont(new Font("SansSerif", Font.BOLD, 22));
        g.drawString("VIRTUAL SCANNER - TEST DOCUMENT", 40, 38);
        // Body text
        g.setColor(Color.BLACK);
        g.setFont(new Font("SansSerif", Font.BOLD, 16));
        g.drawString("Scanner Bridge - Mock Output", 40, 110);
        g.setFont(new Font("SansSerif", Font.PLAIN, 13));
        String[] lines = {
            "This document was generated by the virtual scanner (MockScannerImpl).",
            "It simulates a real WIA scanner response for integration testing.",
            "",
            "Profile: test",
            "Timestamp: " + java.time.LocalDateTime.now(),
            "",
            "If you see this in production, the test profile is active — fix immediately."
        };
        int y = 145;
        for (String line : lines) {
            g.drawString(line, 40, y);
            y += 22;
        }
        // Border
        g.setColor(new Color(0xcccccc));
        g.drawRect(20, 20, 754, 1083);
        g.dispose();
        // Encode as BMP
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ImageIO.write(image, "BMP", bos);
        return List.of(bos.toByteArray());
    }

    @Override
    public List<String> listScanners() {
        return List.of("Virtual Scanner (Test Mode)");
    }
}
